//
// AddressType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Address type */
public enum AddressType: String, Codable, CaseIterable {
    case street = "STREET"
    case postal = "POSTAL"
}
