//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Address details */
public struct Address: Codable { 


    /** Entity Id (primary key) */
    public var id: Int
    public var type: AddressType
    /** Address line */
    public var addressLine1: String
    /** Address line */
    public var addressLine2: String?
    /** Suburb */
    public var suburb: String?
    /** State */
    public var state: String?
    /** Post code */
    public var postCode: String?

    public init(id: Int, type: AddressType, addressLine1: String, addressLine2: String?, suburb: String?, state: String?, postCode: String?) {
        self.id = id
        self.type = type
        self.addressLine1 = addressLine1
        self.addressLine2 = addressLine2
        self.suburb = suburb
        self.state = state
        self.postCode = postCode
    }

}
