//
// Answer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Question Answer */
public struct Answer: Codable { 


    /** Answer text */
    public var text: String

    public init(text: String) {
        self.text = text
    }

}
