//
// BrokerDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Broker details. */
public struct BrokerDetails: Codable { 


    /** Broker Id (email) */
    public var id: String?
    /** Broker&#39;s Client ( current selected) */
    public var client: String

    public init(id: String?, client: String) {
        self.id = id
        self.client = client
    }

}
