//
// FileType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** File Type */
public enum FileType: String, Codable, CaseIterable {
    case business = "BUSINESS"
    case farm = "FARM"
}
