//
// FileUploadType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** File Upload Types */
public enum FileUploadType: String, Codable, CaseIterable {
    case survey = "SURVEY"
    case document = "DOCUMENT"
}
