//
// InsuredDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Insured details */
public struct InsuredDetails: Codable { 


    /** Insured name */
    public var firstname: String?
    /** Insured surname */
    public var surname: String?
    /** Insured mobile */
    public var mobile: String?
    /** Insured email */
    public var email: String
    /** Insured company name */
    public var companyName: String?
    /** Insured trading name */
    public var tradingName: String?
    /** Insured position */
    public var position: String?

    public init(firstname: String?, surname: String?, mobile: String?, email: String, companyName: String?, tradingName: String?, position: String?) {
        self.firstname = firstname
        self.surname = surname
        self.mobile = mobile
        self.email = email
        self.companyName = companyName
        self.tradingName = tradingName
        self.position = position
    }

}
