//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Location. */
public struct Location: Codable { 


    /** Entity Id (primary key) */
    public var id: Int
    /** Location name */
    public var name: String
    /** Location addresses */
    public var addresses: [Address]?

    public init(id: Int, name: String, addresses: [Address]?) {
        self.id = id
        self.name = name
        self.addresses = addresses
    }

}
