//
// PhoneType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Phone types */
public enum PhoneType: String, Codable, CaseIterable {
    case fax = "FAX"
    case mobile = "MOBILE"
    case work = "WORK"
}
