//
// QuestionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Question Types */
public enum QuestionType: String, Codable, CaseIterable {
    case text = "TEXT"
    case radiogroup = "RADIOGROUP"
    case dropdown = "DROPDOWN"
    case checkboxes = "CHECKBOXES"
    case boolean = "BOOLEAN"
    case comment = "COMMENT"
}
