//
// Question.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Question: Codable { 


    public var type: QuestionType
    /** Question text */
    public var text: String
    /** An array of question answers */
    public var answers: [Answer]

    public init(type: QuestionType, text: String, answers: [Answer]) {
        self.type = type
        self.text = text
        self.answers = answers
    }

}
