//
// RequestSurvey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RequestSurvey: Codable { 


    /** Survey Id */
    public var surveyId: String

    public init(surveyId: String) {
        self.surveyId = surveyId
    }

}
