//
// ResponseSurveyQuestions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ResponseSurveyQuestions: Codable { 


    /** Survey Id */
    public var surveyId: String
    /** The list of questions returned. If the filter results in an empty set then this array may have no records. */
    public var questions: [Question]

    public init(surveyId: String, questions: [Question]) {
        self.surveyId = surveyId
        self.questions = questions
    }

}
