//
// ResponseUpload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ResponseUpload: Codable { 


    /** Survey Id */
    public var surveyId: String

    public init(surveyId: String) {
        self.surveyId = surveyId
    }

}
