//
// SurveyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Survey details. */
public struct SurveyResponse: Codable { 


    /** Reference (Survey Id) */
    public var reference: UUID?
    /** Folder Id */
    public var folderId: String?
    public var broker: BrokerDetails?
    public var insured: InsuredDetails?
    /** Survey JSON Document */
    public var survey: String?
    /** Message (could be error) */
    public var message: String?

    public init(reference: UUID?, folderId: String?, broker: BrokerDetails?, insured: InsuredDetails?, survey: String?, message: String?) {
        self.reference = reference
        self.folderId = folderId
        self.broker = broker
        self.insured = insured
        self.survey = survey
        self.message = message
    }

}
