//
// SurveyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SurveyRequest: Codable { 


    /** Reference (Survey Id) */
    public var reference: UUID?
    /** Folder Id */
    public var folderId: String?
    public var broker: BrokerDetails?
    public var insured: InsuredDetails?
    /** Survey JSON Document */
    public var survey: String?

    public init(reference: UUID?, folderId: String?, broker: BrokerDetails?, insured: InsuredDetails?, survey: String?) {
        self.reference = reference
        self.folderId = folderId
        self.broker = broker
        self.insured = insured
        self.survey = survey
    }

}
