//
// SurveyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SurveyResponse: Codable { 


    /** Reference (Survey Id) */
    public var reference: String

    public init(reference: String) {
        self.reference = reference
    }

}
