//
// SurveyAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class SurveyAPI {
    /**
     Get Survey Questions
     
     - parameter xV: (header) Version of the API end point requested by the client. Must be set to a positive integer. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers). 
     - parameter surveyRequest: (body) Survey Request (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func surveyQuestions(xV: String, surveyRequest: RequestSurvey? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ResponseSurvey?,_ error: Error?) -> Void)) {
        surveyQuestionsWithRequestBuilder(xV: xV, surveyRequest: surveyRequest).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Survey Questions
     - POST /survey/questions
     - Obtain a list of survey questions
     - responseHeaders: [x-v(String)]
     - parameter xV: (header) Version of the API end point requested by the client. Must be set to a positive integer. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers). 
     - parameter surveyRequest: (body) Survey Request (optional)
     - returns: RequestBuilder<ResponseSurvey> 
     */
    open class func surveyQuestionsWithRequestBuilder(xV: String, surveyRequest: RequestSurvey? = nil) -> RequestBuilder<ResponseSurvey> {
        let path = "/survey/questions"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: surveyRequest)

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-v": xV.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ResponseSurvey>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

}
