/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package au.com.totemsoft.openbanking.cds.v1.api;

import java.util.Optional;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.com.totemsoft.openbanking.cds.v1.model.ResponseCommonDiscoveryStatus;
import au.com.totemsoft.openbanking.cds.v1.model.ResponseDiscoveryOutagesList;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@Validated
@Api(value = "discovery", description = "the discovery API")
public interface DiscoveryApi {

    DiscoveryApi getDelegate();

    /**
     * GET /discovery/outages : Get Outages
     * Obtain a list of scheduled outages for the implementation
     *
     * @param xV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers) (required)
     * @param xMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. (optional)
     * @return Success (status code 200)
     */
    @ApiOperation(value = "Get Outages", nickname = "getOutages", notes = "Obtain a list of scheduled outages for the implementation", response = ResponseDiscoveryOutagesList.class, tags={ "Common","Discovery", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ResponseDiscoveryOutagesList.class) })
    @RequestMapping(value = "/discovery/outages",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ResponseDiscoveryOutagesList> getOutages(@ApiParam(value = "Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)" ,required=true) @RequestHeader(value="x-v", required=true) String xV,@ApiParam(value = "Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable." ) @RequestHeader(value="x-min-v", required=false) Optional<String> xMinV) {
        return getDelegate().getOutages(xV, xMinV);
    }


    /**
     * GET /discovery/status : Get Status
     * Obtain a health check status for the implementation
     *
     * @param xV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers) (required)
     * @param xMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. (optional)
     * @return Success (status code 200)
     */
    @ApiOperation(value = "Get Status", nickname = "getStatus", notes = "Obtain a health check status for the implementation", response = ResponseCommonDiscoveryStatus.class, tags={ "Common","Discovery", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ResponseCommonDiscoveryStatus.class) })
    @RequestMapping(value = "/discovery/status",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ResponseCommonDiscoveryStatus> getStatus(@ApiParam(value = "Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)" ,required=true) @RequestHeader(value="x-v", required=true) String xV,@ApiParam(value = "Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable." ) @RequestHeader(value="x-min-v", required=false) Optional<String> xMinV) {
        return getDelegate().getStatus(xV, xMinV);
    }

}
