# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
    Elixir Survey 
     Lambda function using an SQS Queue as the trigger and SQS queues as destinations

Globals:
  Api:
    #Auth: []
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 15

Description: AWS Serverless Spring API - au.com.totemsoft.serverless.elixir::elixir-service

Parameters:
  ServerlessRestApi:
    Type: String
    Default: '8cyv1loyhf'
#   CognitoUserPoolId:
#     Type: String
#     Default: 'Yhf0y3epT'

Resources:
  # SQS Queue to receive a message on successful Lambda execution
  #OnSuccessDestinationSQSQueue:
  #  Type: AWS::SQS::Queue

  # Destinations CloudFormation configuration
#   ElixirEventInvokeConfig:
#     Type: AWS::Lambda::EventInvokeConfig
#     Properties:
#       FunctionName:
#         Ref: ElixirServiceFunction
#       Qualifier: '$LATEST'
#       MaximumEventAgeInSeconds: 600
#       MaximumRetryAttempts: 0
#       DestinationConfig:
#         OnSuccess:
#           Destination: arn:aws:sqs:ap-southeast-2:708851056257:elixir-survey
#         OnFailure:
#           Destination: arn:aws:sns:ap-southeast-2:708851056257:elixir-xir

  # Define Amazon Cognito User Pool
  ElixirApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      OpenApiVersion: '2.0'
      Auth:
        DefaultAuthorizer: ElixirCognitoAuthorizer
        Authorizers:
          ElixirCognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${AWS::Region}_Yhf0y3epT
            AuthorizationScopes:
              - elixir/read
              - elixir/write
            Identity:
              Header: 'Authorization'

  # Define Function(s)
  ElixirServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: au.com.totemsoft.serverless.elixir.StreamLambdaHandler::handleRequest
      Runtime: java8
      Policies:
      - AmazonSQSFullAccess
      - AmazonSNSFullAccess
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          AWS_WORKDOCS_FOLDER: c41a559256c02428d916089d86487e66d64e205cd5125cd41ea75860c16b3316
      Events:
        health:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId:
              Ref: ElixirApi
            Auth:
              Authorizer: NONE
        surveyQuestions:
          Type: Api
          Properties:
            Path: /survey/questions
            Method: post
            RestApiId:
              Ref: ElixirApi
        surveyUpload:
          Type: Api
          Properties:
            Path: /survey/upload
            Method: post
            RestApiId:
              Ref: ElixirApi

Outputs:
  ElixirServiceApi:
    Description: URL for application
    Value:
      Fn::Sub: 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: ElixirServiceApi
