swagger: "2.0"
info:
  title: Elixir Survey
  description: API sets created by the Totem Software Pty Ltd to meet the needs of the Survey
  version: 1.0.0
  contact:
    name: Valeri Chibaev
    url: http://totemsoft.com.au/
    email: totemsoft.com.au@gmail.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/
host: survey.holder.com.au
basePath: /survey-au/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
#
# The securityDefinitions section is used to define all security schemes (authentication types) supported by the API.
securityDefinitions:
  BasicAuth:
    type: basic
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
# paths
paths:
  /survey/questions:
    post:
      summary: Get Survey Questions
      description: Obtain a list of survey questions
      operationId: surveyQuestions
      security: [] # No security
      x-scopes:
        - survey:question.basic:read
      tags:
        - Survey
      parameters:
        - $ref: '#/parameters/RequestHeader_x-v'
        - $ref: '#/parameters/RequestSurvey'
      responses:
        200:
          description: Success
          headers:
            x-v:
              type: string
              description: The [version](#response-headers) of the API end point that the data holder has responded with.
          schema:
            $ref: '#/definitions/ResponseSurvey'
      x-version: 1
  /survey/upload:
    post:
      summary: Uploads a file.
      description: Uploads a file.
      operationId: surveyUpload
      security:
        - OAuth2: [write]
      x-scopes:
        - survey:question.basic:upload
      tags:
        - Survey
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: fileUpload
          type: file
          required: true
          description: The file to upload.
        - in: formData
          name: fileNote
          type: string
          required: false
          description: Description of file contents.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ResponseUpload'
        401:
          description: Not authenticated
        403:
          description: Access token does not have the required scope
# parameters
parameters:
  RequestHeader_x-v:
    name: x-v
    description: Version of the API end point requested by the client. Must be set to a positive integer. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers).
    in: header
    type: string
    required: true
  RequestSurvey:
    name: surveyRequest
    in: body
    description: Survey Request
    required: true
    schema:
      $ref: '#/definitions/RequestSurvey'
# definitions
definitions:
  RequestSurvey:
    type: object
    required:
      - surveyId
    properties:
      surveyId:
        description: Survey Id
        type: string
  ResponseSurvey:
    type: object
    required:
      - surveyId
      - questions
    properties:
      surveyId:
        description: Survey Id
        type: string
      questions:
        description: The list of questions returned. If the filter results in an empty set then this array may have no records.
        type: array
        items:
          $ref: '#/definitions/Question'
  Question:
    type: object
    required:
      - type
      - text
      - answers
    properties:
      type:
        $ref: '#/definitions/QuestionType'
      text:
        type: string
        description: Question text
      answers:
        description: An array of question answers
        type: array
        items:
          $ref: '#/definitions/Answer'
  QuestionType:
    type: string
    description: Question Types
    enum:
      - TEXT
      - RADIOGROUP
      - DROPDOWN
      - CHECKBOXES
      - BOOLEAN
      - COMMENT
  Answer:
    type: object
    description: Question Answer
    required:
      - text
    properties:
      text:
        type: string
        description: Answer text
  ResponseUpload:
    type: object
    required:
      - surveyId
    properties:
      surveyId:
        description: Survey Id
        type: string
