swagger: "2.0"
info:
  title: Elixir Survey
  description: API sets created by the Totem Software Pty Ltd to meet the needs of the Survey
  version: 1.0.0
  contact:
    name: Valeri Chibaev
    url: http://totemsoft.com.au/
    email: totemsoft.com.au@gmail.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/
host: ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
#
# The securityDefinitions section is used to define all security schemes (authentication types) supported by the API.
# securityDefinitions:
#   OAuth2:
#     type: oauth2
#     flow: accessCode
#     authorizationUrl: https://elixir.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize
#     tokenUrl: https://elixir.auth.${AWS::Region}.amazoncognito.com/oauth2/token
#     scopes:
#       read: Grants read access
#       write: Grants write access
#       admin: Grants read and write access to administrative information
paths:
  /survey:
    post:
      summary: Get/Create Survey
      description: Obtain a survey (will create one if does not exists)
      operationId: survey
      tags:
        - Survey
      parameters:
        - $ref: '#/parameters/RequestSurvey'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ResponseSurvey'
  /survey/questions:
    post:
      summary: Get Survey Questions
      description: Obtain a list of survey questions
      operationId: surveyQuestions
      tags:
        - Survey
      parameters:
        - $ref: '#/parameters/RequestReference'
        - $ref: '#/parameters/RequestSurvey'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ResponseSurveyQuestions'
  /survey/upload:
    post:
      summary: Uploads a file.
      description: Uploads a file.
      operationId: surveyUpload
      tags:
        - Survey
      consumes:
        - multipart/form-data
      parameters:
        - $ref: '#/parameters/RequestReference'
        - in: formData
          name: fileUpload
          type: file
          required: true
          description: The file to upload.
        - in: formData
          name: fileNote
          type: string
          required: false
          description: Description of file content.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/ResponseUpload'
        401:
          description: Not authenticated
        403:
          description: Access token does not have the required scope
#
# parameters
#
parameters:
  RequestReference:
    name: reference
    description: Reference of request. See [HTTP Headers](#request-headers).
    in: header
    type: string
    required: true
  RequestSurvey:
    name: surveyRequest
    in: body
    description: Survey Request
    required: true
    schema:
      $ref: '#/definitions/RequestSurvey'
#
# definitions
#
definitions:
  #
  RequestSurvey:
    type: object
    required:
      - surveyId
    properties:
      reference:
        description: Reference
        type: string
      surveyId:
        description: Survey Id
        type: string
  #
  ResponseSurvey:
    type: object
    required:
      - reference
      - surveyId
    properties:
      reference:
        description: Reference
        type: string
      surveyId:
        description: Survey Id
        type: string
  #
  ResponseSurveyQuestions:
    type: object
    required:
      - surveyId
      - questions
    properties:
      surveyId:
        description: Survey Id
        type: string
      questions:
        description: The list of questions returned. If the filter results in an empty set then this array may have no records.
        type: array
        items:
          $ref: '#/definitions/Question'
  Question:
    type: object
    required:
      - type
      - text
      - answers
    properties:
      type:
        $ref: '#/definitions/QuestionType'
      text:
        type: string
        description: Question text
      answers:
        description: An array of question answers
        type: array
        items:
          $ref: '#/definitions/Answer'
  QuestionType:
    type: string
    description: Question Types
    enum:
      - TEXT
      - RADIOGROUP
      - DROPDOWN
      - CHECKBOXES
      - BOOLEAN
      - COMMENT
  Answer:
    type: object
    description: Question Answer
    required:
      - text
    properties:
      text:
        type: string
        description: Answer text
  # 
  ResponseUpload:
    type: object
    required:
      - surveyId
    properties:
      surveyId:
        description: Survey Id
        type: string
