openapi: 3.0.1
info:
  title: Elixir Survey
  description: API sets created by the Totem Software Pty Ltd to meet the needs of
    the Survey
  contact:
    name: Valeri Chibaev
    url: http://totemsoft.com.au/
    email: totemsoft.com.au@gmail.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/
  version: 1.0.0
servers:
- url: ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/
paths:
  /client/find:
    get:
      summary: Receives all clients.
      description: Receives all clients for a user.
      operationId: findClients
      responses:
        200:
          description: An array of Client(s)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientResponse'
  /client/find/{userId}:
    get:
      summary: Receives all clients.
      description: Receives all clients for a user.
      operationId: findClientsByUser
      parameters:
      - name: userId
        in: path
        description: User Id
        required: true
        schema:
          type: string
      responses:
        200:
          description: An array of Client(s)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientResponse'
  /survey/create:
    post:
      summary: Create Survey.
      description: Create Survey for user (current selected client/location).
      operationId: createSurvey
      parameters:
      - name: client
        in: header
        description: Client Name
        required: true
        schema:
          type: string
      - name: location
        in: header
        description: Location Name
        schema:
          type: string
      requestBody:
        description: Survey Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveyRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveySummaryResponse'
      x-codegen-request-body-name: surveyRequest
  /survey/find:
    get:
      summary: Find all Surveys for user.
      description: Find all Surveys for user (current selected client/location).
      operationId: findSurveys
      parameters:
      - name: client
        in: header
        description: Client Name
        required: true
        schema:
          type: string
      - name: location
        in: header
        description: Location Name
        schema:
          type: string
      responses:
        200:
          description: An array of SurveyResponse(s)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SurveySummaryResponse'
  /survey/find/{reference}/{folderId}:
    get:
      summary: Get Survey.
      description: Get Survey (by reference).
      operationId: findSurvey
      parameters:
      - name: client
        in: header
        description: Client Name
        required: true
        schema:
          type: string
      - name: location
        in: header
        description: Location Name
        schema:
          type: string
      - name: reference
        in: path
        description: Reference (Survey Id)
        required: true
        schema:
          type: string
          format: UUID
      - name: folderId
        in: path
        description: Folder Id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyResponse'
  /survey/update:
    put:
      summary: Update Survey.
      description: Update Survey (for reference).
      operationId: updateSurvey
      parameters:
      - name: client
        in: header
        description: Client Name
        required: true
        schema:
          type: string
      - name: location
        in: header
        description: Location Name
        schema:
          type: string
      requestBody:
        description: Survey Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveyRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyResponse'
      x-codegen-request-body-name: surveyRequest
  /survey/upload/{reference}/{folderId}/{fileName}:
    post:
      summary: Upload a file.
      description: Uploads a file (for Survey).
      operationId: upload
      parameters:
      - name: reference
        in: path
        description: Reference (Survey Id)
        required: true
        schema:
          type: string
          format: UUID
      - name: folderId
        in: path
        description: Folder Id
        required: true
        schema:
          type: string
      - name: fileName
        in: path
        description: File Name
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          image/png:
            schema:
              type: string
              #format: binary
              format: base64
#          multipart/form-data:
#            schema:
#              type: object
#              properties:
#                body:
#                  type: string
#                  format: binary
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        401:
          description: Not authenticated
          content: {}
        403:
          description: Access token does not have the required scope
          content: {}
  /survey/download/{reference}/{folderId}:
    get:
      summary: Download a file.
      description: Download a file (for Survey).
      operationId: download
      parameters:
      - name: reference
        in: path
        description: Reference (Survey Id)
        required: true
        schema:
          type: string
          format: UUID
      - name: folderId
        in: path
        description: Folder Id
        required: true
        schema:
          type: string
      - name: filename
        in: query
        description: File name
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/*:
              schema:
                type: string
                format: binary
            image/*:
              schema:
                type: string
                format: binary
        404:
          description: File not found
          content: {}
components:
  schemas:
    Reference:
      type: string
      description: Reference (Survey Id)
      format: UUID
    Id:
      type: integer
      description: Entity Id (primary key)
    FolderId:
      type: string
      description: Folder Id
    DocumentId:
      type: string
      description: Document Id
    Message:
      type: string
      description: Message (could be error)
    SurveyRequest:
      type: object
      properties:
        reference:
          $ref: '#/components/schemas/Reference'
        folderId:
          $ref: '#/components/schemas/FolderId'
        broker:
          $ref: '#/components/schemas/BrokerDetails'
        insured:
          $ref: '#/components/schemas/InsuredDetails'
        survey:
          $ref: '#/components/schemas/SurveyDocument'
    SurveySummaryResponse:
      type: object
      properties:
        reference:
          $ref: '#/components/schemas/Reference'
        folderId:
          $ref: '#/components/schemas/FolderId'
        message:
          $ref: '#/components/schemas/Message'
      description: Survey Summary details.
    SurveyResponse:
      type: object
      properties:
        reference:
          $ref: '#/components/schemas/Reference'
        folderId:
          $ref: '#/components/schemas/FolderId'
        broker:
          $ref: '#/components/schemas/BrokerDetails'
        insured:
          $ref: '#/components/schemas/InsuredDetails'
        survey:
          $ref: '#/components/schemas/SurveyDocument'
        message:
          $ref: '#/components/schemas/Message'
      description: Survey details.
    UploadResponse:
      required:
      - documentId
      - reference
      type: object
      properties:
        reference:
          $ref: '#/components/schemas/Reference'
        documentId:
          $ref: '#/components/schemas/DocumentId'
        message:
          $ref: '#/components/schemas/Message'
    SurveyDocument:
      type: string
      description: Survey JSON Document
    FileType:
      type: string
      description: File Type
      enum:
      - BUSINESS
      - FARM
    AddressType:
      type: string
      description: Address type
      enum:
      - STREET
      - POSTAL
    Address:
      required:
      - addressLine1
      - id
      - type
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        type:
          $ref: '#/components/schemas/AddressType'
        addressLine1:
          type: string
          description: Address line
        addressLine2:
          type: string
          description: Address line
        suburb:
          type: string
          description: Suburb
        state:
          type: string
          description: State
        postCode:
          type: string
          description: Post code
      description: Address details
    PhoneType:
      type: string
      description: Phone types
      enum:
      - FAX
      - MOBILE
      - WORK
    Phone:
      title: Phone details
      required:
      - number
      - type
      type: object
      properties:
        type:
          $ref: '#/components/schemas/PhoneType'
        number:
          type: string
    Location:
      title: Location.
      required:
      - id
      - name
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
          description: Location name
        addresses:
          type: array
          description: Location addresses
          items:
            $ref: '#/components/schemas/Address'
      description: Location.
    ClientResponse:
      title: Client
      required:
      - company
      - email
      - firstName
      - lastName
      type: object
      properties:
        company:
          type: string
          description: Client's company name (has to be unique)
        tradingName:
          type: string
          description: Client's trading name
        firstName:
          type: string
          description: Client's firstname
        lastName:
          type: string
          description: Client's surname
        email:
          type: string
          description: Client's email
        position:
          type: string
          description: Client's position
        phones:
          type: array
          description: Client's phones
          items:
            $ref: '#/components/schemas/Phone'
        addresses:
          type: array
          description: Client's addresses
          items:
            $ref: '#/components/schemas/Address'
        locations:
          type: array
          description: Client's locations
          items:
            $ref: '#/components/schemas/Location'
      description: Client details
    InsuredDetails:
      title: InsuredDetails
      required:
      - email
      type: object
      properties:
        firstname:
          type: string
          description: Insured name
        surname:
          type: string
          description: Insured surname
        mobile:
          type: string
          description: Insured mobile
        email:
          type: string
          description: Insured email
        companyName:
          type: string
          description: Insured company name
        tradingName:
          type: string
          description: Insured trading name
        position:
          type: string
          description: Insured position
      description: Insured details
    BrokerDetails:
      title: Broker Details.
      required:
      - client
      type: object
      properties:
        id:
          type: string
          description: Broker Id (email)
        client:
          type: string
          description: Broker's Client ( current selected)
      description: Broker details.
  parameters:
    RequestHeader_Client:
      name: client
      in: header
      description: Client Name
      required: true
      schema:
        type: string
    RequestHeader_Location:
      name: location
      in: header
      description: Location Name
      schema:
        type: string
    UserId:
      name: userId
      in: path
      description: User Id
      required: true
      schema:
        type: string
    Reference:
      name: reference
      in: path
      description: Reference (Survey Id)
      required: true
      schema:
        type: string
        format: UUID
    FolderId:
      name: folderId
      in: path
      description: Folder Id
      required: true
      schema:
        type: string
    Filename:
      name: filename
      in: query
      description: File name
      required: true
      schema:
        type: string
  requestBodies:
    SurveyRequest:
      description: Survey Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SurveyRequest'
      required: true
