swagger: "2.0"
info:
  title: Elixir Survey
  description: API sets created by the Totem Software Pty Ltd to meet the needs of the Survey
  version: 1.0.0
  contact:
    name: Valeri Chibaev
    url: http://totemsoft.com.au/
    email: totemsoft.com.au@gmail.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/
host: ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
#
# The securityDefinitions section is used to define all security schemes (authentication types) supported by the API.
# securityDefinitions:
#   OAuth2:
#     type: oauth2
#     flow: accessCode
#     authorizationUrl: https://elixir.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize
#     tokenUrl: https://elixir.auth.${AWS::Region}.amazoncognito.com/oauth2/token
#     scopes:
#       read: Grants read access
#       write: Grants write access
#       admin: Grants read and write access to administrative information
paths:
  /survey/create:
    post:
      summary: Create Survey
      description: Create Survey
      operationId: create
      parameters:
        - $ref: '#/parameters/SurveyRequest'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/SurveyResponse'
  /survey/find/{reference}:
    get:
      summary: Get Survey
      description: Get Survey
      operationId: find
      parameters:
        - $ref: '#/parameters/Reference'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/SurveyResponse'
  /survey/update:
    put:
      summary: Update Survey
      description: Update Survey
      operationId: update
      parameters:
        - $ref: '#/parameters/SurveyRequest'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/SurveyResponse'
  /survey/upload/{reference}:
    post:
      summary: Uploads a file.
      description: Uploads a file.
      operationId: upload
      consumes:
        - multipart/form-data
      parameters:
        - $ref: '#/parameters/Reference'
        - in: formData
          name: fileUpload
          type: file
          required: true
          description: The file to upload.
        - in: formData
          name: fileNote
          type: string
          required: false
          description: Description of file content.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/UploadResponse'
        401:
          description: Not authenticated
        403:
          description: Access token does not have the required scope
#
# parameters
#
parameters:
  Reference:
    in: path
    name: reference
    description: Reference (Survey Id)
    type: string
    format: UUID
    required: true
  SurveyRequest:
    name: surveyRequest
    in: body
    description: Survey Request
    required: true
    schema:
      $ref: '#/definitions/SurveyRequest'
#
# definitions
#
definitions:
  #
  Reference:
    description: Reference (Survey Id)
    type: string
    format: UUID
  #
  Message:
    description: Message (could be error)
    type: string
  #
  SurveyRequest:
    type: object
    required:
      - reference
    properties:
      reference:
        $ref: '#/definitions/Reference'
  #
  SurveyResponse:
    type: object
    required:
      - reference
    properties:
      reference:
        $ref: '#/definitions/Reference'
      message:
        $ref: '#/definitions/Message'
  # 
  UploadResponse:
    type: object
    required:
      - reference
    properties:
      reference:
        $ref: '#/definitions/Reference'
      message:
        $ref: '#/definitions/Message'
  #
  FileUploadType:
    type: string
    description: File Upload Types
    enum:
      - SURVEY
      - DOCUMENT
